### ISSUE TITLE
Please check com2us game

### ISSUE THREAD

**Issue by xtbtvd12399** [wDCat/ANRC#13]
I run Summoners war game on android 6.0.1 but after the game has been loaded, it got force close. Can you fix it? Thanks!

**Comment by xtbtvd12399** [comment]
Here is that game
https://play.google.com/store/apps/details?id=com.com2us.smon.normal.freefull.google.kr.android.common
Or i will upload a catlog if you need. :D

**Comment by wDCat** [comment]
yeah i run this game and found some problem.i'm finding another way to deal with it.

**Comment by xtbtvd12399** [comment]
Hope you can solve it soon. Thank you :D

**Comment by xtbtvd12399** [comment]
Game still got fc in ver 0.0.29. HOpe u can fix it. Thanks :-)

**Comment by wDCat** [comment]
add this game and select "bypass xigncode"

**Comment by Mulano77** [comment]
Dont work with bypass xigncode or root hide... app closed with errorcode

**Comment by Mulano77** [comment]
http://www.bilder-upload.eu/upload/07a11c-1478110658.png

**Comment by wDCat** [comment]
@Mulano77 It just adds Appguard to check xposed and root.

**Comment by Mulano77** [comment]
Phone have root and other Module worked with xposed v86 :( if I deinstall ANRC, message pops up with "xbridge.blablabla detected"

**Comment by wDCat** [comment]
@Mulano77  try the latest version v0.0.43
download at here: https://github.com/wDCat/ANRC/tree/master/releases
Select "root hide" "AC Patch" and "Don't kill me" options.

**Comment by xtbtvd12399** [comment]
i will try it now. thank you

**Comment by xtbtvd12399** [comment]
Its work atm. Thank you very much <3 <3 <3

**Comment by xtbtvd12399** [comment]
Can you fix randomize automic start on next release? Thank you :heart_eyes:

**Comment by wDCat** [comment]
@xtbtvd12399 ANRC randomize automic start?

**Comment by xtbtvd12399** [comment]
At version 0.0.43. Version 0.0.51 is fixed.
But ver 51 isnt work on my new rom. Is it work on your phone? Maybe my Framework got problem. Please reply me if on your phone ver 51 still work. Thank you.

**Comment by xtbtvd12399** [comment]
Sometimes, when i open an app (that isnt in the "hide apps" list), It is still show the messenger "ANRC is granted to be superuser".

**Comment by xtbtvd12399** [comment]
No problem found!
