### ISSUE TITLE
Regenerate Fail! error

### ISSUE THREAD

**Issue by trickart** [wDCat/ANRC#14]
When installing ANRC (or running "Regenerate the file" in Advanced Setting),I have an error message.
<img src="https://cloud.githubusercontent.com/assets/4015060/19461022/e56219c4-951b-11e6-9d83-ccf1baa8986f.png" height="300">

I checked SuperSU log, ANRC  failed chown.
<img src="https://cloud.githubusercontent.com/assets/4015060/19461136/e9252ba4-951c-11e6-9a5a-86c7ea39ad96.png" height="300">

**Comment by wDCat** [comment]
fixed at version 0.0.25
but I can not reproduce this error msg.
please try the new version and send me a reply._(:зゝ∠)_

**Comment by trickart** [comment]
Thanks! I tried 0.0.25 in SCL23 (Galaxy S5 KDDI Model).
Although no longer error of SuperSU log, I got an "Regenerate Fail! " message...
I decide to play in another device that can use ANRC.

**Comment by wDCat** [comment]
maybe it is caused by KNOX.
