### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by stephenjudge** [wDCat/ANRC#29]
Can you please document how to reverse the changes to system files made by ANC and clean uninstall ANC. Thank you.

**Comment by wDCat** [comment]
Yeah...I will add a button to remove these files next version.

**Comment by dwilliamson1066** [comment]
Hi wDCat, a clean uninstall button is a great idea. Until this is ready could you list the changes made so we can uninstall manually? Thanks!

**Comment by wDCat** [comment]
Remove this dir & file:
/data/d_self_area/
/system/lib/libanrc.so
/system/lib/libanrc.log.so
/system/lib/libxigncode_anrc.so

If you had replaced /system/bin/pm,
remove /system/bin/pm and rename /system/bin/pm_orig to /system/bin/pm

**Comment by dwilliamson1066** [comment]
That's great! Thanks!!
FYI - only uninstalling because it didn't work on the app I installed it for - Halifax mobile banking app. Looking around it seems like a difficult one to get working with root
