### ISSUE TITLE
Still detect freedom on netmarbles games

### ISSUE THREAD

**Issue by exodius48** [wDCat/ANRC#34]
Im using ANRC on miui 8 but it can't be bypass freedom.
Would it be pissible to fixed?

**Comment by encell** [comment]
MIUI 8 here (Xiao mi mi5 global rom 6.0.1M - I don't want to update to 7.0N).
Everything working perfect, don't use Freedom, use Lucky Patcher.

**Comment by exodius48** [comment]
Work on latest version.
Closed now.
