### ISSUE TITLE
0.0.58无法隐藏日版智龙迷城

### ISSUE THREAD

**Issue by faynwol** [wDCat/ANRC#41]
nexus 6P 6.0.1 MTC20L
jp.gungho.pad
卡在启动时的黑屏界面>.<

**Comment by wDCat** [comment]
试试29版的~

**Comment by faynwol** [comment]
29和31都闪退XD
不过安装完有个异常
![image](https://cloud.githubusercontent.com/assets/2764772/20885580/a33aec74-bb2c-11e6-9634-69b1a8712668.png)

**Comment by wDCat** [comment]
先关闭SElinux ，然后进设置重装支持库

**Comment by faynwol** [comment]
O了，大感谢！
