### ISSUE TITLE
建议添加免责声明.

### ISSUE THREAD

**Issue by giveup** [wDCat/ANRC#45]
我的设备在安装之后,发现它没有按预期的效果运行.于是清除支持库,重启.
发现完全超出我预期的效果了,app再也检测不出我是否root了,因为root失效了.
进recovery重新安装supersu也无法获得root权限.
建议添加一个免责声明让用户考虑清楚是否真的要使用这个module.

**Comment by wDCat** [comment]
嗯。。。这个应用并不会对root相关的文件进行修改，所以并不会造成你所述的那种情况。
