### ISSUE TITLE
ANRC Support for NA Version of Fate Grand Order (Error 60 and 92 affects) No Update for ANRC to support NA

### ISSUE THREAD

**Issue by darkzamurai** [wDCat/ANRC#89]
@wDCat  Can I ask a question if your xposed module support the newly release server of Fate Grand Order USA?..... Because they had developer option and root ban.... Thanks

**Comment by AkagiShiroe** [comment]
i tested that "backup" and its work.. they use same things as JP Version (beside translation and a bit change in some texture which include text).. so yes ANRC should support both since they "are" use same method(more likely they do that to protect from reroll spamer). @wDCat wait her to answer to verify 👍

**Comment by darkzamurai** [comment]
What is that "backup"?

**Comment by wDCat** [comment]
just a memu image backup,you can download it at the end of https://github.com/wDCat/ANRC/issues/77.

ANRC will not work fine these days.

**Comment by darkzamurai** [comment]
The USA version not JP I mean @wDCat 
Nah maybe I'll watch on YouTube when it releases..... :-(

![screenshot_2017-06-25-19-36-38](https://user-images.githubusercontent.com/27139746/27516633-2c3fb51a-59f0-11e7-9e96-f80472b5c05e.png)

**Comment by RinFallen** [comment]
I tested FGO English version on Memu and it worked :)

**Comment by RinFallen** [comment]
Waiting for new patch ANRC to play FGO English ver on Nox :)

**Comment by darkzamurai** [comment]
![screenshot_2017-06-20-21-25-44](https://user-images.githubusercontent.com/27139746/27516690-7278692c-59f1-11e7-9d73-c6b03392e11c.png)
I'll have this on my China Server (Biligame) with these specs
Samsung Galaxy Tab 2 7.0 GT P3110
Android 5.1.1 (Rooted with Gltools for low graphics)
1 GB Ram Dual Core
16GB Storage

2 years playing on JPN
1 year above playing on China

**Comment by RinFallen** [comment]
@darkzamurai : Tbh i really hate China server :< Becuz font doesn't fit my eyes :(

**Comment by darkzamurai** [comment]
But in terms of performance I like it because I can play 5 hours of it and for those cheaters they banning them by player codes......

**Comment by darkzamurai** [comment]
Maybe I have no hope on playing the NA Version, July is near all the pre register items will expire..... Saber Lily will gone

**Comment by AkagiShiroe** [comment]
@darkzamurai need an account? i have plenty.. A LOT.. because reroll with my own method.

**Comment by darkzamurai** [comment]
@AkagiShiroe thanks but I can't play because I have 1gb and trying to test with gltools and also waiting for android republic mods to release but they maybe put on their VIP mods..... And also YouTube videos are few..... :-(

**Comment by ricelover7** [comment]
@AkagiShiroe I'd like one if you could save an account for me with the pre-registration rewards. That would be great since I'm unwilling to unroot my device.

**Comment by darkzamurai** [comment]
Nah I'll concentrate on my China Server and Rashoumon is coming...... But I'll watch on memes of US Version......

**Comment by keyserjaya** [comment]
I fixed the problem by uninstalling Xposed Installer app =)

**Comment by darkzamurai** [comment]
@keyserjaya how did you do that?..... How matter I try did not work for me.....

**Comment by keyserjaya** [comment]
Well i got error: 92
It says something about Xposed.
After that i found there's Xposed Installer app installed on my phone. So i
uninstall it. And now i can play Fate GO :)

**Comment by darkzamurai** [comment]
Its long time that the NA was release no hope for @wDCat to release the update..... :(

**Comment by darkzamurai** [comment]
:-(

**Comment by darkzamurai** [comment]
I don't think @wDCat can handle the FGO NA and JP on android anymore just like old times..... :-(
