### ISSUE TITLE
Hidden documentation

### ISSUE THREAD

**Issue by AbandonedCart** [wDCat/ANRC#93]
Some options aren't entirely self-explanatory so I was hoping to find documentation.

Catch a cat
AG patch 
Don't kill me (Unclear if this means ANRC / the app being targeted)

This is without even getting into the settings for the library. I came across this module in the Xposed repository and the listing only leads here. Maybe I missed a link somewhere.

**Comment by LoungeKatt** [comment]
It seems no actual support is provided here, either. That is unfortunate...
