### ISSUE TITLE
Fate/GO Error Code 92 (Xposed detected)

### ISSUE THREAD

**Issue by AbandonedCart** [wDCat/ANRC#95]
The original copy of this issue was closed, but the issue remains unresolved. This is here just so anyone else experiencing the issue knows it has been reported. The original issue is at https://github.com/wDCat/ANRC/issues/77

**Comment by AkagiShiroe** [comment]
@LoungeKatt i've close it, due unexpected long reply and some issue with ANRC~, hope @wDCat wDCat ressurected

**Comment by darkzamurai** [comment]
i closed mine too because my sister gave me a new phone i can play JPN, US and China..... don't need root and ANRC...... maybe you can buy VIP on androidrepublic and also they bypass root with hacks......

**Comment by AbandonedCart** [comment]
@AkagiShiroe The issue is still unresolved.
@darkzamurai This is for people still experiencing the issue. AR uses code other people wrote to charge you money for cheating the game. You can possibly bypass root, but also end up banned.

**Comment by AbandonedCart** [comment]
Closing this because Fate/GO, despite being very slow to update, is consistently ahead of this project. This adds more to be detected, rather than preventing detection of existing components.
