### ISSUE TITLE
My observation on magisk and fgo

### ISSUE THREAD

**Issue by athenatan** [wDCat/ANRC#99]
Idk if you already know about this but this is my observation on FGO and Magisk
no magisk (manager app) + no root (from magisk) = can enter FGO
have magisk + no root = cannot enter FGO
no magisk (uninstalled) + no root = can enter FGO
have magisk + have root = cannot enter FGO
no magisk (uninstalled) + have root = cannot enter FGO
Apparently, the game seem to detect files rather than detect the root itself.
How can I get pass through it in this case ?

**Comment by reihunter360** [comment]
Have you tried nonxposed mode?

**Comment by AkagiShiroe** [comment]
cat are busy.. sorry bro~
